let person = "hasan";
let num = 8.0;
let bool = true;
let und;
let sum;
sum = num - person;
let val = null;
console.log(person);
console.log(num);
console.log(bool);
console.log(und);
console.log(sum);
console.log(val);
